### ISSUE TITLE
Website broke tho

### ISSUE THREAD

**Issue by rustom** [christeng12/valorant-wnt#1]
![image](https://user-images.githubusercontent.com/45826892/117100234-da77f300-ad38-11eb-8247-c2e02253ed82.png)

**Comment by christeng12** [comment]
Site is down temporarily for maintenance. Thank you for your patience.

**Comment by rustom** [comment]
haha website go brr

**Comment by rustom** [comment]
💯

**Comment by rustom** [comment]
Great work team
